Сделал задачу 1-task
js-tasks-ru/jsbasic-20220310_fhvfn94 pull request #1
Opened 2022-02-18 17:49 UTC by fhvfn94

2022-02-18 17:49 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @stas-dolgachov должен запустить тесты.

2022-03-10 18:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-10 18:24 UTC, koalex requested changes
Я не смогу принять PR пока не будет решена задача с факториалом

2022-03-17 03:59 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-03-17 03:59 UTC, koalex approved these changes

2022-03-17 04:00 UTC, merged